[build]
  command = "npm run build"  
  publish = "build"  # Make sure this matches your build output directory

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Add proper MIME types
[[headers]]
  for = "/*.json"
    [headers.values]
    Content-Type = "application/json"

[[headers]]
  for = "/*.css"
    [headers.values]
    Content-Type = "text/css"